dist: trusty

language: node_js
node_js:
  - 'node'

branches:
  only:
    - master

script:
  - npm run lint
  - npm run test:ci
  - npm run build
  - npm run deploy:cp

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/line-chat-statistics
  on:
    branch: master
